version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/my_dump.sql:/docker-entrypoint-initdb.d/my_dump.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  prisma-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-api
    depends_on:
      - postgres
    ports:
      - "12345:3000"
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
